### PR TITLE
Upgrade so as make compatible with sbt version 0.13.11.

### PR DESCRIPTION
**Pull request by aholland**
project bintray-sbt plugin 0.1.1 -> 0.3.0 (much altered build.sbt due to significant refactoring of bintray-sbt plugin)
version 0.0.13 -> 0.0.14
sbt.version 0.13.8 -> 0.13.11
play sbt-plugin 2.4.0 -> 2.4.3 (and concomitantly changed import, _root_.play.PlayImport.PlayKeys -> play.sbt.PlayImport.PlayKeys)
scalaVersion 2.10.4 -> 2.10.6 (latest version that will work with Play sbt-plugin, which is not built with any Scala 11.x)
openBrowser method got parameters to show it is called 'for the side-effects'.

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -1,27 +1,18 @@
...
+    organization in ThisBuild := "com.jamesward",
+    sbtPlugin := true,
+    description := "auto refresh for play with scala and scala.js cross project",
+    licenses +=("MIT", url("http://opensource.org/licenses/MIT")),
+    publishMavenStyle := false,
+    javacOptions ++= Seq("-source", "1.8", "-target", "1.8")
+  )
 
 libraryDependencies += "net.databinder" %% "unfiltered-netty-websockets" % "0.8.0"
+bintrayVcsUrl := Some("git@github.com/aholland/play-auto-refresh.git")
```
Comment (jamesward) [inline build.sbt]: Fix the url.

File: build.sbt [hunk 2]
```diff
@@ -1,27 +1,18 @@
...
-organization := "com.jamesward"
-
-scalaVersion := "2.10.4"
-
-javacOptions ++= Seq("-source", "1.8", "-target", "1.8")
-
-version := "0.0.13"
-
-sbtPlugin := true
+lazy val root = (project in file(".")).
```
Comment (jamesward) [inline build.sbt]: Why this style of settings?

Comment (aholland) [inline build.sbt]: Because I followed this guide in order to get it working. http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html

File: build.sbt (hunk 1 above)
Comment (aholland) [inline build.sbt]: done

File: build.sbt (hunk 2 above)
Comment (jamesward) [inline build.sbt]: Those instructions are the old way of providing settings in a `build.sbt` file.

Comment (aholland) [inline build.sbt]: I had a bit of trouble with messages like 
`value BintrayKeys is not a member of sbt.TaskKey[String]`
so I just followed the instructions pretty directly. Happy to make any changes.

Comment (jamesward) [inline build.sbt]: Some / all of those bintray settings are no longer needed with `0.3.0`.  Here is another `build.sbt` that works with `0.3.0`: https://github.com/jamesward/sbt-atom/blob/master/build.sbt

**Comment by jamesward** [comment]
Thanks for working through those changes.  `0.0.14` has been published.  Let me know how it goes.

**Comment by aholland** [comment]
A pleasure. Thanks for the pointers. The reason I cared enough to get this up-to-date and building with the latest version of sbt was because I was attempting to fork your project and alter it as follows: when working with a Play Scala.js project (with `server`, `shared` and `client` sections in the style of https://github.com/vmunier/play-with-scalajs-example) I find that if I am tinkering with the client side and make a change that does not compile (purely on the client, i.e. Scala.js section), it gets reported in the browser just like a server error and when I fix it, the server get reloaded. With database connections etc. that's slow. I later decided that no simple change to your plug-in was going to achieve this because even without your plugin, just using refresh, the same thing occurs. My solution instead is create a contrived set-up with Li Haoyi's `workbench` plugin running in a different process, completely unaware of the server code, and Play configured with `exposedHeaders = ["Access-Control-Allow-Origin"]' so that it can load all the Ajax from the play server. You're clearly the right person to ask, so if you have any better ideas please let me know, thanks!

**Comment by aholland** [comment]
PS why the double line-spacing in `build.sbt` files?

**Comment by jamesward** [comment]
I was hoping that someone would write a Scala.js sbt-web plugin that I think would be the ideal way to combine Play & Scala.js but afaik that doesn't exist yet.  I'm pretty sure this would solve your problem but will be some work.

The `build.sbt` file needs new lines between expressions because there isn't an actual parser for the `.sbt` format yet.  I think the sbt team was trying to fix that but I'm not sure where it went.

**Comment by aholland** [comment]
Thanks James.

**Comment by aholland** [comment]
James, FYI, no plugin yet, but there's this: https://github.com/aholland/play-scalajs-workbench-example
